modLoader="javafml"
loaderVersion="[34,)"
#issueTrackerURL=""
license="MIT"

[[mods]]
modId="resourcefullchickens"
version="${file.jarVersion}"
displayName="ResourceFull Chickens"
#updateJSONURL=""
authors="DMNerd"
description='''
1.16 Resource chickens inspired by Chickens.'''

[[dependencies.resourcefullchickens]]
modId="forge"
mandatory=true
versionRange="[34.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.resourcefullchickens]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3,1.17)"
ordering="NONE"
side="BOTH"